### ISSUE TITLE
can't make tx from blob

### ISSUE THREAD

**Issue by SergeyAnkarenko** [moneroexamples/openmonero#103]
![image](https://user-images.githubusercontent.com/6827668/47392387-2b98dc00-d725-11e8-9dbf-c2b2153c7b56.png)

I am running monero_v9 branch
After some period of time I started to get this error

**Comment by moneroexamples** [comment]
It must be same issue as for the onion explorer -  cant read txs from mempool (https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/152) 

I fixed that in the explorer, but not not yet in the openmonero. Should be done today.

**Comment by SergeyAnkarenko** [comment]
Thanks,

Will it work, if I apply the same change to https://github.com/moneroexamples/openmonero/blob/fc88d67fffffcce9a8b3bf46d36167890b8a8da6/src/CurrentBlockchainStatus.cpp#L475 as it described in the afd168c commit

**Comment by SergeyAnkarenko** [comment]
Oh, it's from different branch, forget about this

**Comment by moneroexamples** [comment]
> forget about this

So it works now?

**Comment by SergeyAnkarenko** [comment]
No, I meant, that the change that I proposed won't work, because I took this https://github.com/moneroexamples/openmonero/blob/fc88d67fffffcce9a8b3bf46d36167890b8a8da6/src/CurrentBlockchainStatus.cpp#L475 from master branch, not monero_v8

The problem still exists

![image](https://user-images.githubusercontent.com/6827668/47410658-3d06d600-d76f-11e8-8d7a-10603e3e29dd.png)

**Comment by moneroexamples** [comment]
Use openmonero from this branch: https://github.com/moneroexamples/openmonero/tree/mymonero_v9
 and also latest monero from its master branch https://github.com/monero-project/monero 

The problem is with moenro's mempool tx format. I think its format changed very recently, so have to be on the most latest version of monero code base.

Also what Linux are you using? If being on the latest versions of monero and openmonero won't help, I will check on same distro (if possible) you have. I'm on Arch Linux and at present cant replicate this issue.

**Comment by stoffu** [comment]
Sorry, this Monero bug was introduced by me in https://github.com/monero-project/monero/pull/4592 and was fixed in https://github.com/monero-project/monero/pull/4635. It's not that the tx format changed or anything. The fix is already in both the master and the release branches.

**Comment by SergeyAnkarenko** [comment]
Thank you all! I will try the most latest monero version.

I am on Ubuntu 16.04

**Comment by SergeyAnkarenko** [comment]
I have tried the latest successfull build for monero (https://github.com/monero-project/monero/commit/e0a1d45d76916c350679e9e076c250dfd4494210)

I am still getting this issue. I will try to reset mysql mymonero db

**Comment by moneroexamples** [comment]
monero-project/monero@e0a1d45 is from 8 days ago. Get current one by git cloning monero master. Here are basic instractions how to do it: https://github.com/moneroexamples/openmonero/tree/mymonero_v9#monero-download-and-compilation

**Comment by SergeyAnkarenko** [comment]
The latest monero version wasn't built successfully on ubuntu (master branch), and I have the same compile errors as I see in their log files
![image](https://user-images.githubusercontent.com/6827668/47421401-3422fe00-d789-11e8-8685-64c056a4be86.png)
https://build.getmonero.org/builders/monero-static-ubuntu-amd64/builds/5721/steps/compile/logs/stdio

Maybe I need to built v0.13 branch. At least it was built succesfully

**Comment by SergeyAnkarenko** [comment]
Ok, so I have build openmonero with latest version of monero (release_v0.13 branch) https://github.com/monero-project/monero/commit/29073f65e8816d4c32b6ffef514943a5650b8d3b 

Error has dissapeared.

![image](https://user-images.githubusercontent.com/6827668/47427448-00e86b00-d799-11e8-99c4-3992080dd0e6.png)

**Comment by SergeyAnkarenko** [comment]
Thanks for your help. 

Also I want to point out that it seems openmonero doesn't know about all the transactions, that I have made during this 'error period', how to resolve this?

It seems I need to start synchronizing monerod from the very first block and start openmonero so it can get information about this lost transactions. Am I right?

**Comment by moneroexamples** [comment]
> It seems I need to start synchronizing monerod from the very first block and start openmonero so it can get information about this lost transactions

If something does not show in openmonero, its openmonero issue most likely. For example, openmonero does not search txs sent to your subaddresses. So these txs will be missing if you did any. 

If something is missing, does it happen on stagenet or testnet? This way, I could check it myself if would would provide me stagenet and/or testnet wallet details.
